<a href="https://colab.research.google.com/github/Fliptoss/ML_stuff/blob/main/Prediction_without_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import pickle

In [6]:
ohe_sex = pickle.load(open('/content/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('/content/ohe_embarked.pkl','rb'))
model = pickle.load(open('/content/clf.pkl','rb'))

In [7]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [8]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [9]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [10]:
test_input_sex

array([[0., 1.]])

In [11]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [12]:
test_input_embarked

array([[0., 0., 1.]])

In [13]:
test_input_age = test_input[:,2].reshape(1,1)

In [14]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [15]:
test_input_transformed.shape

(1, 10)

In [17]:
model.predict(test_input_transformed)

array([1])